INSERT INTO TB_CATEGORY(NAME, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY(NAME) VALUES ('Eletronics');
INSERT INTO TB_CATEGORY(NAME) VALUES ('Computers');
INSERT INTO TB_CATEGORY(NAME) VALUES ('Home utilities');